server:
  port: 8089
  servlet:
    context-path: /api
spring:
  #  Datasource configurations
  datasource:
    #    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:oracle:thin:@localhost:1521/xe
    username: om
    password: om
  #    Email configurations
#  mail:
#    host: smtp.gmail.com
#    port: 587
#    username: hzahidnaeem@gmail.com
#    password: "******"
#    properties:
#      mail:
#        #        transport:
#        #          protocol: smtp
#        smtp:
#          auth: true
#          connectiontimeout: 5000
#          timeout: 5000
#          writetimeout: 5000
#          starttls:
#            enable: true
  #          socketFactory:
  #            port: 465
  #            class: javax.net.ssl.SSLSocketFactory
  #    url: jdbc:mysql://localhost:3306/xxim?useSSL=false&allowPublicKeyRetrieval=true
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.Oracle10gDialect
        enable_lazy_load_no_trans: true
        jdbc:
          batch_size: 20
    show-sql: true
  # Liquibase
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/om-db-changelog-master.xml

debug: true
logging:
  level:
    org:
      hibernate:
        SQL: debug
    liquibase: INFO
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n'
om:
  app:
    jwtSecret: jwtOMSecretKey
    jwtExpiration: 86400
