CREATE OR REPLACE VIEW BOOK_TRANS AS
SELECT 0 TNUM
      ,'ADDED' TRANS_TYPE
      ,V.CREATION_DATE TRANS_DATE
      ,V.VOLUME_ID
      ,V.VOLUME_NAME
      ,B.BOOK_ID
      ,B.BOOK_NAME
  FROM VOLUME V, BOOK B
 WHERE V.BOOK_ID = B.BOOK_ID
UNION ALL
SELECT -1 TNUM
      ,H.TRANS_TYPE
      ,H.TRANS_DATE
      ,L.VOLUME_ID
      ,V.VOLUME_NAME
      ,B.BOOK_ID
      ,B.BOOK_NAME
  FROM BOOK_TRANS_LINE L
      ,BOOK_TRANS_HEADER H
      ,VOLUME V
      ,BOOK B
 WHERE     L.HEADER_ID = H.HEADER_ID
       AND L.VOLUME_ID = V.VOLUME_ID
       AND V.BOOK_ID = B.BOOK_ID
       AND H.TRANS_TYPE = 'ISSUE'
UNION ALL
SELECT 1 TNUM
      ,H.TRANS_TYPE
      ,H.TRANS_DATE
      ,L.VOLUME_ID
      ,V.VOLUME_NAME
      ,B.BOOK_ID
      ,B.BOOK_NAME
  FROM BOOK_TRANS_LINE L
      ,BOOK_TRANS_HEADER H
      ,VOLUME V
      ,BOOK B
 WHERE     L.HEADER_ID = H.HEADER_ID
       AND L.VOLUME_ID = V.VOLUME_ID
       AND V.BOOK_ID = B.BOOK_ID
       AND H.TRANS_TYPE = 'RECEIPT'